# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Flutter get
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter build ipa --no-codesign
        
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          path: /Users/runner/work/MobileApp/MobileApp/build/ios/archive/Runner.xcarchive

